---
title: "<h3>Assignment 8: Split/Apply/Combine: Debt, the Last Seventy Years</h3>"
output: html_document
---

_Agenda_: Practicing split-apply-combine.

<font color="red"><h4>INSTRUCTIONS:</h4></font>
<ul>
<li> Type each one of the R commands in this lesson on the space provided below.
<li> You can embed an R code chunk like this:
```{r}
summary(cars)
```
<li> Before you move to the next step, highlight or move the cursor to the end of the individual R command and click on **Run**. Do this for all R commands.
<li> After you are done click the **Knit HTML**, **Knit PDF** button (upper left window). A document will be generated that includes both content as well as the output of any embedded R code chunks within the document.
<li> Go to File --> Save. Name your file.
<li> Upload the file to the Moodle site by using the link provided.
</ul>
<br>
Gross domestic product (GDP) is a measure of the total market value of all goods and services produced in a given country in a given year. The percentage growth rate of GDP in year $t$ is 
\[
100\times\left(\frac{GDP_{t+1} - GDP_{t}}{GDP_{t}}\right) - 100
\]


An important claim in economics is that the rate of GDP growth is closely related to the level of government debt, specifically with the ratio of the government’s debt to the GDP. The file `debt.csv`, located under the link that is labed Data file for Assignment 8, contains measurements of GDP growth and of the debt-to-GDP ratio for twenty countries around the world, from the 1940s to 2010. Note that not every country has data for the same years, and some years in the middle of the period are missing data for some countries but not others. Click on the Data file for assignment 8 download the file and upload to RStudio.

==========

<font color="red"> <h5>Problem 1. (10 points)</h5></font> Load the data into a dataframe called debt. You should have 1171 rows and 4 columns.

<font color="green"> <h5>Solution</h5></font> Type your answer here

<font color="red"> <h5>Problem 2. (10 points)</h5></font> Calculate the average GDP growth rate for each country (averaging over years). `aggregate`, `split`, and/or `daply` (and of course `mean`). `mean(debt$growth[debt$Country=="Australia"])`, except to check your work. (The average growth rates for Australia and the Netherlands should be 3.72 and 3.03.) Present a table of the twenty growth rates.

<font color="green"> <h5>Solution</h5></font> Type your answer here

<font color="red"> <h5>Problem 3. (10 points)</h5></font> Calculate the average GDP growth rate for each year (averaging over countries).  Again, don't use something like `mean(debt$growth[debt$Year==1972])` except to check your work.  (The average growth rates for 1972 and 1989 should be $5.63$ and $3.19$, respectively.)  Make a plot of the growth rates versus the year.  Make sure the axes are labeled appropriately.

<font color="green"> <h5>Solution</h5></font> Type your answer here

<font color="red"> <h5>Problem 4. (10 points)</h5></font> The function `cor(x,y)` calculates the correlation coefficient between two vectors `x` and `y`.

a. Calculate the correlation coefficient between GDP growth and the debt ratio over the whole data set (all countries, all years).  Your answer should be $-0.1995$.

<font color="green"> <h5>Solution</h5></font> Type your answer here

b. Calculate the correlation coefficient separately for each country, and plot a histogram of these coefficients.  The mean of these correlations should be $-0.1778$.  Do not use a loop.  _Hint_: consider writing a function and then making it an argument to `dplyr()`.

<font color="green"> <h5>Solution</h5></font> Type your answer here

c. Calculate the correlation coefficient separately for each year, and plot a histogram of these coefficients.  The mean of these correlations should be $-0.1906$.

<font color="green"> <h5>Solution</h5></font> Type your answer here

d. Are there any countries or years where the correlation goes against the general trend?

<font color="green"> <h5>Solution</h5></font> Type your answer here

<font color="red"> <h5>Problem 5. (10 points)</h5></font> Make a scatter-plot of GDP growth (vertical) against the debt ratio (horizontal).  Describe the over-all shape of the point cloud in words.  Does its shape match what you expect from problem 4?

<font color="green"> <h5>Solution</h5></font> Type your answer here



<br><font color="red"> <h5>Total Number of Points Earned: XX/50</h5></font>
